//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAHealth.ECM.Ignia.WAHealth.Sublayouts.Story_Renderings {
    
    
    public partial class StoryTwoColumn290 {
        
        /// <summary>
        /// CampaignPanelRepeater control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater CampaignPanelRepeater;
    }
}
